# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: 7.0.x
      - name: Checkout repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Build
        run: dotnet build -c Release ./src
      - name: Publish NuGet package
        run: |
          for pkg in ./src/Luatrauma.Internal.AssemblyPublicizer.MSBuild/bin/Release/*.nupkg; do
            dotnet nuget push "$pkg" \
              --api-key "${{ secrets.NUGET_TOKEN }}" \
              --source https://api.nuget.org/v3/index.json
          done
